"""empty message

Revision ID: 82a431334e54
Revises: None
Create Date: 2016-08-24 12:31:42.203072

"""

# revision identifiers, used by Alembic.
revision = '82a431334e54'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miles', sa.Integer(), nullable=True),
    sa.Column('json_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    ### end Alembic commands ###
